-- CEV-ONBOARD-RPC-46. Fictional sequential Auth compatibility, not live JWT proof.
begin;
alter table auth.users add column if not exists email_confirmed_at timestamptz;
alter table auth.users add column if not exists deleted_at timestamptz;
insert into public.tenants(id,name,trade,timezone) values
 ('46000000-0000-4000-8000-000000000001','Command demo A','HVAC','America/New_York'),
 ('46000000-0000-4000-8000-000000000002','Command demo B','Plumbing','America/Chicago');
insert into auth.users(id,email,email_confirmed_at) select ('46000000-0000-4000-8001-00000000000'||n)::uuid,'command-'||n||'@example.invalid',now() from generate_series(1,9) n;
insert into public.memberships(tenant_id,user_id,role) select '46000000-0000-4000-8000-000000000001',('46000000-0000-4000-8001-00000000000'||n)::uuid,(array['owner','admin','dispatcher','technician','viewer']::public.app_role[])[n] from generate_series(1,5) n;
insert into public.memberships(tenant_id,user_id,role) values('46000000-0000-4000-8000-000000000002','46000000-0000-4000-8001-000000000006','owner');

do $$
declare target uuid:='46000000-0000-4000-8000-000000000001'; request uuid:='46000000-0000-4000-8002-000000000001'; input jsonb; payload jsonb; result jsonb; snapshot jsonb; revision integer:=0; service_id uuid; active_service_id uuid; exception_id uuid; inactive_exception_id uuid; audit_count bigint; n integer; weekday integer;
begin
 if (select count(*) from pg_proc p join pg_namespace s on s.oid=p.pronamespace join pg_roles r on r.oid=p.proowner where s.nspname='public' and p.proname in ('onboarding_configure','onboarding_save_resume','onboarding_snapshot','onboarding_accept_invitation','onboarding_history_list','onboarding_history_reenable') and p.prosecdef and r.rolname='postgres' and 'search_path=""'=any(p.proconfig) and has_function_privilege('authenticated',p.oid,'EXECUTE') and not has_function_privilege('anon',p.oid,'EXECUTE'))<>6 then raise exception 'Guarded RPC ownership/search path/grants'; end if;
 if exists(select 1 from pg_proc p join pg_namespace s on s.oid=p.pronamespace where s.nspname='onboarding_private' and has_function_privilege('authenticated',p.oid,'EXECUTE')) then raise exception 'Private helper execute grant'; end if;
 if onboarding_private.input_size('{"a":1.0,"b":[true,null,"😀"]}')<>octet_length(convert_to('{"a":1,"b":[true,null,"😀"]}','UTF8')) then raise exception 'Parsed compact body sizing parity'; end if;
 payload:='{"name":"Command demo A","trade":"HVAC","timezone":"America/New_York","business_contact_name":"","business_email":null,"business_phone":null}';
 input:=jsonb_build_object('tenant_id',target,'request_id',request,'expected_config_revision',0,'payload',payload);
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000001',true);
 set local role authenticated;
 result:=public.onboarding_configure('save_business_profile',input);
 if result->>'status'<>'saved' or (result->>'config_revision')::integer<>1 then raise exception 'Profile initialize: %',result->>'status'; end if;
 result:=public.onboarding_configure('save_business_profile',input);
 if result->>'status'<>'replayed' or (result->>'version')::integer<>1 then raise exception 'Profile replay'; end if;
 result:=public.onboarding_configure('save_business_profile',jsonb_set(input,'{payload,name}','"  Command demo A  "'));
 if result->>'status'<>'replayed' then raise exception 'Normalized profile digest differs'; end if;
 result:=public.onboarding_configure('save_business_profile',jsonb_set(input,'{payload,name}','"Different"'));
 if result->>'reason'<>'request_reuse' then raise exception 'Request reuse not denied'; end if;
 result:=public.onboarding_configure('save_business_profile',jsonb_set(input,'{request_id}',to_jsonb(gen_random_uuid())));
 if result->>'reason'<>'revision' then raise exception 'Stale revision not denied'; end if;
 result:=public.onboarding_configure('save_business_profile',input||'{"role":"owner"}');
 if result->>'status'<>'validation_error' then raise exception 'Injected role not denied'; end if;
 result:=public.onboarding_configure('save_business_profile',jsonb_set(input,'{payload,name}','""'));
 if result->>'status'<>'validation_error' then raise exception 'Empty tenant authority accepted'; end if;
 reset role;
 select count(*) into audit_count from public.audit_events where tenant_id=target;
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',1,'payload',payload);
 set local role authenticated;
 result:=public.onboarding_configure('save_business_profile',input);
 if result->>'status'<>'saved' or result->>'version'<>'1' then raise exception 'No-op revision'; end if;
 reset role;
 if (select count(*) from public.audit_events where tenant_id=target)<>audit_count then raise exception 'No-op business audit'; end if;
 payload:=payload||'{"name":"Authority changed","business_contact_name":"Demo office","business_email":"office@example.invalid"}';
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',1,'payload',payload);
 set local role authenticated;
 result:=public.onboarding_configure('save_business_profile',input);
 if result->>'status'<>'saved' or result->>'config_revision'<>'2' then raise exception 'Profile authority/contact double bump or failed: %',result->>'status'; end if;
 reset role;
 if (select business_contact_name from public.tenant_business_profiles where tenant_id=target)<>'Demo office' then raise exception 'Contact did not persist'; end if;
 payload:=payload||'{"business_contact_name":"Changed contact"}';
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',2,'payload',payload);
 set local role authenticated;
 result:=public.onboarding_configure('save_business_profile',input);
 if result->>'status'<>'saved' or result->>'config_revision'<>'3' then raise exception 'Contact-only revision'; end if;
 revision:=3;
 -- New service, replay null ID, retained omission, and foreign ID denial.
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"items":[{"id":null,"name":"","description":"Draft","enabled":true,"position":0}]}'::jsonb);
 result:=public.onboarding_configure('replace_services',input);
 if result->>'status'<>'saved' then raise exception 'Service create: %',result->>'status'; end if;
 revision:=4; result:=public.onboarding_configure('replace_services',input);
 if result->>'status'<>'replayed' then raise exception 'Null-ID service replay'; end if;
 reset role;
 if (select count(*) from public.tenant_services where tenant_id=target)<>1 then raise exception 'Duplicate replay service'; end if;
 select id into service_id from public.tenant_services where tenant_id=target;
 set local role authenticated;
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"items":[]}'::jsonb);
 result:=public.onboarding_configure('replace_services',input); revision:=5;
 if result->>'status'<>'saved' then raise exception 'Service omission'; end if;
 result:=public.onboarding_configure('replace_services',jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload',jsonb_build_object('items',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'name','','description','','enabled',true,'position',0)))));
 if result->>'status'<>'unavailable' then raise exception 'Foreign/unknown service ID'; end if;
 reset role;
 if (select enabled from public.tenant_services where id=service_id) or (select count(*) from public.tenant_services where tenant_id=target)<>1 then raise exception 'Omission erased identity'; end if;
 -- Whole explicit week, normalization and saved draft empty-open state.
 select jsonb_build_object('days',jsonb_agg(jsonb_build_object('weekday',w,'closed',false,'intervals','[]'::jsonb) order by w desc)) into payload from generate_series(0,6) w;
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload',payload);
 set local role authenticated;
 result:=public.onboarding_configure('replace_weekly_hours',input); revision:=6;
 if result->>'status'<>'saved' then raise exception 'Weekly save: %',result->>'status'; end if;
 select jsonb_build_object('days',jsonb_agg(jsonb_build_object('weekday',w,'closed',false,'intervals','[]'::jsonb) order by w)) into payload from generate_series(0,6) w;
 result:=public.onboarding_configure('replace_weekly_hours',input||jsonb_build_object('payload',payload));
 if result->>'status'<>'replayed' then raise exception 'Week ordering digest differs'; end if;
 result:=public.onboarding_configure('replace_weekly_hours',input||jsonb_build_object('request_id',gen_random_uuid(),'expected_config_revision',revision));
 if result->>'version'<>'6' then raise exception 'Week sort no-op'; end if;
 result:=public.onboarding_configure('replace_weekly_hours',jsonb_set(input,'{payload,days}','[]'));
 if result->>'status'<>'validation_error' then raise exception 'Incomplete week accepted'; end if;
 -- Exception retained date identity, removal and re-add.
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"date":"2028-02-29","closed":false,"intervals":[{"start_minute":600,"end_minute":660},{"start_minute":540,"end_minute":600}]}'::jsonb);
 result:=public.onboarding_configure('upsert_hours_exception',input); revision:=7; exception_id:=(result->>'id')::uuid;
 if result->>'status'<>'saved' or exception_id is null then raise exception 'Exception save'; end if;
 result:=public.onboarding_configure('remove_hours_exception',jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"date":"2028-02-29"}'::jsonb)); revision:=8;
 if result->>'status'<>'saved' or result->>'id'<>exception_id::text then raise exception 'Exception removal'; end if;
 result:=public.onboarding_configure('upsert_hours_exception',input||jsonb_build_object('request_id',gen_random_uuid(),'expected_config_revision',revision)); revision:=9;
 if result->>'status'<>'saved' or result->>'id'<>exception_id::text then raise exception 'Exception re-add identity'; end if;
 result:=public.onboarding_configure('remove_hours_exception',jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"date":"2029-01-01"}'::jsonb));
 if result->>'status'<>'saved' or result->'id'<>'null'::jsonb or result->>'version'<>'9' then raise exception 'Absent removal not no-op'; end if;
 -- Safe request-only booking and sensitive escalation.
 result:=public.onboarding_configure('save_booking_preferences',jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"lead_time_minutes":null,"buffer_before_minutes":0,"buffer_after_minutes":0,"horizon_days":null,"notes":"Office review","acknowledged":false}'::jsonb)); revision:=10;
 if result->>'status'<>'saved' then raise exception 'Booking preference save'; end if;
 result:=public.onboarding_configure('replace_escalation_contacts',jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"items":[{"id":null,"label":"Office","contact_name":"Fictional contact","email":"escalation@example.invalid","phone":null,"enabled":true,"position":0}]}'::jsonb)); revision:=11;
 if result->>'status'<>'saved' then raise exception 'Escalation save'; end if;
 reset role;
 insert into public.tenant_services(id,tenant_id,name,description,enabled,position) values(gen_random_uuid(),target,'Active current service','Current editor row',true,1) returning id into active_service_id;
 insert into public.tenant_escalation_contacts(id,tenant_id,label,contact_name,email,phone,enabled,position) values(gen_random_uuid(),target,'Disabled retained contact','Retained contact','retained-escalation@example.invalid',null,false,1);
 insert into public.tenant_hours_exceptions(id,tenant_id,local_date,closed,intervals,active) values(gen_random_uuid(),target,date '2031-01-01',true,'[]'::jsonb,false) returning id into inactive_exception_id;
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_version',0,'step_id','hours');
 set local role authenticated;
 result:=public.onboarding_save_resume(input);
 if result->>'status'<>'saved' or result->>'version'<>'1' or result->>'config_revision'<>'11' then raise exception 'Resume save: %',result->>'status'; end if;
 result:=public.onboarding_save_resume(input); if result->>'status'<>'replayed' then raise exception 'Resume replay'; end if;
 result:=public.onboarding_snapshot(target); snapshot:=result->'snapshot';
 if result->>'status'<>'available' or snapshot->>'projection'<>'owner_setup' or snapshot->>'resume_step'<>'hours' or snapshot->'readiness'->>'configuration_state'<>'not_evaluated' or snapshot->'readiness'->>'providerConnectionAuthorized'<>'false' or snapshot ? 'receipts' then raise exception 'Owner projection/readiness'; end if;
 if jsonb_array_length(snapshot->'services')<>1 or snapshot->'services'->0->>'id'<>active_service_id::text or snapshot->'services'->0->>'enabled'<>'true' then raise exception 'Owner current service projection not bounded active'; end if;
 if jsonb_array_length(snapshot->'escalation')<>1 or snapshot->'escalation'->0->>'email'<>'escalation@example.invalid' or snapshot->'escalation'->0->>'enabled'<>'true' then raise exception 'Owner current escalation projection not bounded active'; end if;
 if exists(select 1 from jsonb_array_elements(snapshot->'exceptions') item where item->>'active'<>'true' or item->>'id'=inactive_exception_id::text) then raise exception 'Owner current exception projection leaked inactive history'; end if;
 reset role;
 if not exists(select 1 from public.tenant_services where id=service_id and not enabled) or not exists(select 1 from public.tenant_escalation_contacts where tenant_id=target and not enabled) or not exists(select 1 from public.tenant_hours_exceptions where id=inactive_exception_id and not active) then raise exception 'Retained inactive history was not preserved in storage'; end if;
 -- Each current role and foreign owner, including denial of replays after demotion.
 for n in 1..6 loop
  perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-00000000000'||n,true); set local role authenticated;
  result:=public.onboarding_snapshot(target);
  if n=6 then if result->>'status'<>'unavailable' then raise exception 'Cross-tenant read'; end if;
  elsif n=3 then if result->'snapshot'->>'projection'<>'dispatcher_operations' or (result->'snapshot') ?| array['profile','escalation','readiness','resume_step','invitations','receipts'] or jsonb_array_length(result->'snapshot'->'services')<>1 or result->'snapshot'->'services'->0->>'enabled'<>'true' then raise exception 'Dispatcher privacy/current projection'; end if;
  elsif n>=4 then if result->'snapshot'->>'projection'<>'workspace' or (result->'snapshot') ?| array['services','profile','escalation'] then raise exception 'Field/viewer projection'; end if;
  else if result->'snapshot'->>'projection'<>'owner_setup' then raise exception 'Office read'; end if; end if;
  result:=public.onboarding_configure('remove_hours_exception',jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"date":"2029-01-01"}'::jsonb));
  if n<=2 then if result->>'status'<>'saved' then raise exception 'Office write'; end if; else if result->>'status'<>'unavailable' then raise exception 'Denied-role write'; end if; end if;
  begin perform 1 from public.tenant_business_profiles; raise exception 'Direct table exposed'; exception when insufficient_privilege then null; end;
  begin perform onboarding_private.advance_revision(target); raise exception 'Private helper exposed'; exception when insufficient_privilege then null; end;
  reset role;
 end loop;
 update public.memberships set role='viewer' where tenant_id=target and user_id='46000000-0000-4000-8001-000000000001';
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000001',true); set local role authenticated;
 result:=public.onboarding_save_resume(input); if result->>'status'<>'unavailable' then raise exception 'Demoted resume replay'; end if;
 reset role;
 update public.memberships set role='owner' where tenant_id=target and user_id='46000000-0000-4000-8001-000000000001';
 update auth.users set email_confirmed_at=null where id='46000000-0000-4000-8001-000000000001';
 set local role authenticated; result:=public.onboarding_snapshot(target); if result->>'status'<>'unavailable' then raise exception 'Unconfirmed user authorized'; end if; reset role;
 update auth.users set email_confirmed_at=now() where id='46000000-0000-4000-8001-000000000001';
 -- First absent exception removal initializes metadata once, without a phantom row.
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000006',true);
 input:=jsonb_build_object('tenant_id','46000000-0000-4000-8000-000000000002','request_id',gen_random_uuid(),'expected_config_revision',0,'payload','{"date":"2030-01-01"}'::jsonb);
 set local role authenticated; result:=public.onboarding_configure('remove_hours_exception',input);
 if result->>'status'<>'saved' or result->'id'<>'null'::jsonb or result->>'version'<>'1' then raise exception 'First absent removal initialization'; end if; reset role;
 if exists(select 1 from public.tenant_hours_exceptions where tenant_id='46000000-0000-4000-8000-000000000002') then raise exception 'Absent removal invented row'; end if;
 set local role anon;
 begin perform public.onboarding_snapshot(target); raise exception 'Anonymous RPC granted'; exception when insufficient_privilege then null; end;
 reset role;
end; $$;
-- Fictional privately provisioned invitations, no issuance/delivery command.
insert into onboarding_private.invitations(id,tenant_id,recipient_user_id,recipient_email,intended_role,token_digest,expires_at,creation_request_id,created_at)
values
 ('46000000-0000-4000-8004-000000000001','46000000-0000-4000-8000-000000000001','46000000-0000-4000-8001-000000000007','command-7@example.invalid','dispatcher',onboarding_private.token_digest(repeat('A',43)),clock_timestamp()+interval '1 hour',gen_random_uuid(),clock_timestamp()-interval '2 hours'),
 ('46000000-0000-4000-8004-000000000002','46000000-0000-4000-8000-000000000001','46000000-0000-4000-8001-000000000007','command-7@example.invalid','dispatcher',onboarding_private.token_digest(repeat('B',42)||'A'),clock_timestamp()+interval '1 hour',gen_random_uuid(),clock_timestamp()-interval '2 hours'),
 ('46000000-0000-4000-8004-000000000003','46000000-0000-4000-8000-000000000001','46000000-0000-4000-8001-000000000008','command-8@example.invalid','viewer',onboarding_private.token_digest(repeat('C',42)||'A'),clock_timestamp()-interval '1 hour',gen_random_uuid(),clock_timestamp()-interval '2 hours'),
 ('46000000-0000-4000-8004-000000000004','46000000-0000-4000-8000-000000000001','46000000-0000-4000-8001-000000000009','command-9@example.invalid','technician',onboarding_private.token_digest(repeat('D',42)||'A'),clock_timestamp()+interval '1 hour',gen_random_uuid(),clock_timestamp()-interval '2 hours');
create function onboarding_private.test_receipt_fault() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'Fictional receipt fault' using errcode='XX000'; end; $$;
revoke all on function onboarding_private.test_receipt_fault() from public,anon,authenticated;
do $$
declare input jsonb:=jsonb_build_object('request_id','46000000-0000-4000-8005-000000000001','token',repeat('A',43)); result jsonb; original_time text; audits bigint; target uuid:='46000000-0000-4000-8000-000000000001'; token_input jsonb;
begin
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000008',true); set local role authenticated;
 result:=public.onboarding_accept_invitation(input); if result->>'status'<>'unavailable' then raise exception 'Wrong recipient'; end if;
 result:=public.onboarding_accept_invitation(jsonb_build_object('request_id',gen_random_uuid(),'token',repeat('C',42)||'A')); if result->>'status'<>'unavailable' then raise exception 'Expired pending invite'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000007',true); set local role authenticated;
 result:=public.onboarding_accept_invitation(input);
 if result->>'status'<>'accepted' or result->>'role'<>'dispatcher' or result->>'entry'<>'setup' or result ?| array['token','email','digest'] then raise exception 'Acceptance: %',result->>'status'; end if;
 original_time:=result->'acceptance'->>'accepted_at';
 if original_time !~ 'Z$' then raise exception 'Acceptance timestamp not UTC'; end if;
 reset role;
 if (select role from public.memberships where tenant_id=target and user_id='46000000-0000-4000-8001-000000000007')<>'dispatcher' then raise exception 'Membership did not persist'; end if;
 select count(*) into audits from public.audit_events where tenant_id=target;
 set local role authenticated;
 result:=public.onboarding_accept_invitation(input);
 if result->>'status'<>'replayed' or result->'acceptance'->>'accepted_at'<>original_time then raise exception 'Invite replay'; end if;
 result:=public.onboarding_accept_invitation(jsonb_set(input,'{request_id}',to_jsonb(gen_random_uuid())));
 if result->>'status'<>'already_accepted' or result->'acceptance'->>'accepted_at'<>original_time then raise exception 'New-request accepted repeat'; end if;
 result:=public.onboarding_accept_invitation(jsonb_set(input,'{token}',to_jsonb(repeat('B',42)||'A')));
 if result->>'reason'<>'request_reuse' then raise exception 'Token/request collision'; end if;
 reset role;
 if (select count(*) from onboarding_private.receipts where actor_user_id='46000000-0000-4000-8001-000000000007' and command='invite_accept')<>2 or (select count(*) from public.audit_events where tenant_id=target)<>audits then raise exception 'Repeat receipt/business audit semantics'; end if;
 update public.tenants set name='Fresh authorized name' where id=target;
 set local role authenticated;
 result:=public.onboarding_accept_invitation(input);
 if result->'workspace'->>'name'<>'Fresh authorized name' or result->'acceptance'->>'accepted_at'<>original_time then raise exception 'Immutable outcome/fresh projection'; end if;
 reset role;
 update auth.users set email='changed@example.invalid' where id='46000000-0000-4000-8001-000000000007';
 set local role authenticated; result:=public.onboarding_accept_invitation(input); if result->>'status'<>'unavailable' then raise exception 'Changed current email replay'; end if; reset role;
 update auth.users set email='command-7@example.invalid',deleted_at=now() where id='46000000-0000-4000-8001-000000000007';
 set local role authenticated; result:=public.onboarding_accept_invitation(input); if result->>'status'<>'unavailable' then raise exception 'Deleted current account replay'; end if; reset role;
 update auth.users set deleted_at=null,email_confirmed_at=null where id='46000000-0000-4000-8001-000000000007';
 set local role authenticated; result:=public.onboarding_accept_invitation(input); if result->>'status'<>'unavailable' then raise exception 'Unconfirmed replay'; end if; reset role;
 update auth.users set email_confirmed_at=now() where id='46000000-0000-4000-8001-000000000007';
 update public.memberships set role='viewer' where tenant_id=target and user_id='46000000-0000-4000-8001-000000000007';
 set local role authenticated; result:=public.onboarding_accept_invitation(input); if result->>'status'<>'unavailable' then raise exception 'Demoted accepted replay'; end if;
 result:=public.onboarding_accept_invitation(jsonb_build_object('request_id',gen_random_uuid(),'token',repeat('B',42)||'A')); if result->>'status'<>'membership_conflict' then raise exception 'Pending role mismatch promoted member'; end if; reset role;
 delete from public.memberships where tenant_id=target and user_id='46000000-0000-4000-8001-000000000007';
 set local role authenticated; result:=public.onboarding_accept_invitation(input); if result->>'status'<>'unavailable' then raise exception 'Removed member restored'; end if; reset role;
 if exists(select 1 from public.memberships where tenant_id=target and user_id='46000000-0000-4000-8001-000000000007') then raise exception 'Replay recreated membership'; end if;
 insert into public.memberships(tenant_id,user_id,role) values(target,'46000000-0000-4000-8001-000000000007','dispatcher');
 update onboarding_private.invitations set status='revoked',revoked_by='46000000-0000-4000-8001-000000000001',revoked_at=clock_timestamp(),version=version+1 where id='46000000-0000-4000-8004-000000000001';
 set local role authenticated; result:=public.onboarding_accept_invitation(input); if result->>'status'<>'unavailable' then raise exception 'Revoked receipt replay'; end if; reset role;
 -- Receipt fault after membership/invite/audit mutations must roll back all.
 create trigger onboarding_test_receipt_fault before insert on onboarding_private.receipts for each row execute function onboarding_private.test_receipt_fault();
 select count(*) into audits from public.audit_events where tenant_id=target;
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000009',true); set local role authenticated;
 token_input:=jsonb_build_object('request_id',gen_random_uuid(),'token',repeat('D',42)||'A');
 result:=public.onboarding_accept_invitation(token_input); if result->>'status'<>'retryable_failure' then raise exception 'Receipt fault not safe'; end if; reset role;
 if exists(select 1 from public.memberships where tenant_id=target and user_id='46000000-0000-4000-8001-000000000009') or (select status from onboarding_private.invitations where id='46000000-0000-4000-8004-000000000004')<>'pending' or (select count(*) from public.audit_events where tenant_id=target)<>audits then raise exception 'Partial failed acceptance'; end if;
 drop trigger onboarding_test_receipt_fault on onboarding_private.receipts;
 set local role authenticated; result:=public.onboarding_accept_invitation(token_input); if result->>'status'<>'accepted' then raise exception 'Retry after failed receipt'; end if; reset role;
 -- Historical acceptance fixture: token expired after its original acceptance.
 update onboarding_private.invitations set status='accepted',accepted_by=recipient_user_id,accepted_at=clock_timestamp()-interval '90 minutes',version=version+1 where id='46000000-0000-4000-8004-000000000003';
 insert into public.memberships(tenant_id,user_id,role) values(target,'46000000-0000-4000-8001-000000000008','viewer');
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000008',true);
 token_input:=jsonb_build_object('request_id',gen_random_uuid(),'token',repeat('C',42)||'A');
 set local role authenticated; result:=public.onboarding_accept_invitation(token_input);
 if result->>'status'<>'already_accepted' then raise exception 'Expired accepted repeat denied'; end if;
 original_time:=result->'acceptance'->>'accepted_at'; result:=public.onboarding_accept_invitation(token_input);
 if result->>'status'<>'replayed' or result->'acceptance'->>'accepted_at'<>original_time then raise exception 'Expired accepted replay denied'; end if; reset role;
end; $$;
do $$
declare result jsonb; input jsonb; revision integer; audits bigint; profile_value text; target uuid:='46000000-0000-4000-8000-000000000001';
begin
 select config_revision into revision from public.tenant_setup_state where tenant_id=target;
 select business_contact_name into profile_value from public.tenant_business_profiles where tenant_id=target;
 select count(*) into audits from public.audit_events where tenant_id=target;
 create trigger onboarding_test_receipt_fault before insert on onboarding_private.receipts for each row execute function onboarding_private.test_receipt_fault();
 perform set_config('request.jwt.claim.sub','46000000-0000-4000-8001-000000000001',true);
 input:=jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'payload','{"name":"Fresh authorized name","trade":"HVAC","timezone":"America/New_York","business_contact_name":"Faulted contact","business_email":null,"business_phone":null}'::jsonb);
 set local role authenticated; result:=public.onboarding_configure('save_business_profile',input);
 if result->>'status'<>'retryable_failure' then raise exception 'Config receipt fault not safe'; end if; reset role;
 if (select config_revision from public.tenant_setup_state where tenant_id=target)<>revision or (select business_contact_name from public.tenant_business_profiles where tenant_id=target)<>profile_value or (select count(*) from public.audit_events where tenant_id=target)<>audits then raise exception 'Partial failed configuration'; end if;
 drop trigger onboarding_test_receipt_fault on onboarding_private.receipts;
 set local role authenticated; result:=public.onboarding_configure('save_business_profile',input);
 if result->>'status'<>'saved' or (result->>'version')::integer<>revision+1 then raise exception 'Config retry after receipt fault'; end if; reset role;
 update public.tenant_setup_state set config_revision=2147483647,version=2147483647 where tenant_id=target;
 input:=input||jsonb_build_object('request_id',gen_random_uuid(),'expected_config_revision',2147483647,'payload',(input->'payload')||'{"name":"Overflow change"}');
 set local role authenticated; result:=public.onboarding_configure('save_business_profile',input);
 if result->>'reason'<>'version_exhausted' then raise exception 'Exhaustion not denied'; end if; reset role;
 if (select name from public.tenants where id=target)<>'Fresh authorized name' then raise exception 'Exhaustion changed authority'; end if;
end; $$;

do $$
declare target uuid:='46000000-0000-4000-8000-000000000002'; owner_id uuid:='46000000-0000-4000-8001-000000000006'; dispatcher_id uuid:='46000000-0000-4000-8001-000000000003'; other_admin_id uuid:='46000000-0000-4000-8001-000000000001'; result jsonb; page1 jsonb; cursor_value text; tampered_cursor text; revision integer; disabled_service uuid; second_service uuid; foreign_service uuid; disabled_contact uuid; inactive_exception uuid; req uuid; n integer;
begin
 reset role;
 insert into public.memberships(tenant_id,user_id,role) values(target,dispatcher_id,'dispatcher') on conflict do nothing;
 insert into public.memberships(tenant_id,user_id,role) values(target,other_admin_id,'admin') on conflict do nothing;
 insert into public.tenant_services(id,tenant_id,name,description,enabled,position) values(gen_random_uuid(),target,'Archived maintenance','Hidden description term',false,2) returning id into disabled_service;
 insert into public.tenant_services(id,tenant_id,name,description,enabled,position) values(gen_random_uuid(),target,'Archived install','Second disabled service',false,3) returning id into second_service;
 insert into public.tenant_escalation_contacts(id,tenant_id,label,contact_name,email,phone,enabled,position) values(gen_random_uuid(),target,'Archived office','Fictional Manager','history-private@example.invalid',null,false,1) returning id into disabled_contact;
 insert into public.tenant_hours_exceptions(id,tenant_id,local_date,closed,intervals,active) values(gen_random_uuid(),target,date '2031-12-24',true,'[]'::jsonb,false) returning id into inactive_exception;
 insert into public.tenant_services(id,tenant_id,name,description,enabled,position) values(gen_random_uuid(),'46000000-0000-4000-8000-000000000001','Foreign retained','Foreign',false,88) returning id into foreign_service;
 perform set_config('request.jwt.claim.sub',owner_id::text,true); set local role authenticated;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services','limit',1));
 if result->>'status'<>'available' or result->>'kind'<>'services' or jsonb_array_length(result->'items')<>1 or result->'page'->>'has_more'<>'true' or result ?| array['receipts','request_id','token'] then raise exception 'Service history page failed: %',result; end if;
 page1:=result; cursor_value:=result->'page'->>'next_cursor';
 if cursor_value !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' or cursor_value like '%Archived%' or cursor_value like '%history-private%' then raise exception 'History cursor not opaque'; end if;
 tampered_cursor:=overlay(cursor_value placing case when substring(cursor_value from 1 for 1)='0' then '1' else '0' end from 1 for 1);
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services','limit',1,'cursor',tampered_cursor));
 if result->>'status'<>'unavailable' then raise exception 'Tampered same-scope cursor accepted'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub',other_admin_id::text,true); set local role authenticated;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services','limit',1,'cursor',cursor_value));
 if result->>'status'<>'unavailable' then raise exception 'Other actor cursor accepted'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub',owner_id::text,true); set local role authenticated;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services','limit',1,'cursor',cursor_value));
 if result->>'status'<>'available' or result->'items'->0->>'id'=page1->'items'->0->>'id' then raise exception 'History cursor did not advance'; end if;
 reset role;
 update onboarding_private.history_cursors set created_at=clock_timestamp()-interval '2 seconds', expires_at=clock_timestamp()-interval '1 second' where id=cursor_value::uuid;
 set local role authenticated;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services','limit',1,'cursor',cursor_value));
 if result->>'status'<>'unavailable' then raise exception 'Expired cursor accepted'; end if;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services','state','all_retained','limit',1,'cursor',cursor_value));
 if result->>'status'<>'unavailable' then raise exception 'Mismatched cursor accepted'; end if;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services','search','Hidden description term'));
 if result->>'status'<>'available' or jsonb_array_length(result->'items')<>0 then raise exception 'Service search leaked description'; end if;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','escalation_contacts','search','history-private@example.invalid'));
 if result->>'status'<>'available' or jsonb_array_length(result->'items')<>0 then raise exception 'Contact search leaked email'; end if;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','escalation_contacts'));
 if result->>'status'<>'available' or result->'items'->0->>'email'<>'history-private@example.invalid' then raise exception 'Owner contact history missing'; end if;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','date_exceptions','sort','local_date'));
 if result->>'status'<>'available' or result->'items'->0->>'id'<>inactive_exception::text or result->'items'->0->>'state'<>'inactive' then raise exception 'Date history missing'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub',dispatcher_id::text,true); set local role authenticated;
 result:=public.onboarding_history_list(jsonb_build_object('tenant_id',target,'kind','services'));
 if result->>'status'<>'unavailable' then raise exception 'Dispatcher read history'; end if;
 reset role;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 select config_revision into revision from public.tenant_setup_state where tenant_id=target;
 set local role authenticated;
 req:=gen_random_uuid();
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',req,'expected_config_revision',revision,'kind','services','row_id',disabled_service,'payload',jsonb_build_object('name','Restored maintenance','description','Restored','position',4)));
 if result->>'status'<>'saved' or result->>'entity'<>'history_reenable' or result->>'id'<>disabled_service::text or (result->>'config_revision')::integer<>revision+1 then raise exception 'Service re-enable failed: %',result; end if;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',req,'expected_config_revision',revision,'kind','services','row_id',disabled_service,'payload',jsonb_build_object('name','Restored maintenance','description','Restored','position',4)));
 if result->>'status'<>'replayed' then raise exception 'History re-enable replay failed'; end if;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',req,'expected_config_revision',revision,'kind','services','row_id',disabled_service,'payload',jsonb_build_object('name','Changed reuse','description','Restored','position',4)));
 if result->>'reason'<>'request_reuse' then raise exception 'History request reuse allowed'; end if;
 reset role;
 select config_revision into revision from public.tenant_setup_state where tenant_id=target;
 set local role authenticated;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision-1,'kind','services','row_id',second_service,'payload',jsonb_build_object('name','Stale','description','Stale','position',5)));
 if result->>'reason'<>'revision' then raise exception 'History stale revision allowed'; end if;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'kind','services','row_id',foreign_service,'payload',jsonb_build_object('name','Foreign','description','Foreign','position',5)));
 if result->>'status'<>'unavailable' then raise exception 'Foreign history row disclosed'; end if;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'kind','date_exceptions','row_id',inactive_exception,'payload','{"date":"2031-12-25","closed":true,"intervals":[]}'::jsonb));
 if result->>'status'<>'validation_error' then raise exception 'Date mismatch accepted'; end if;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'kind','date_exceptions','row_id',inactive_exception,'payload','{"date":"2031-12-24","closed":false,"intervals":[{"start_minute":600,"end_minute":540}]}'::jsonb));
 if result->>'status'<>'validation_error' then raise exception 'Invalid interval accepted'; end if;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'kind','date_exceptions','row_id',inactive_exception,'payload','{"date":"2031-12-24","closed":true,"intervals":[]}'::jsonb));
 if result->>'status'<>'saved' or result->>'id'<>inactive_exception::text then raise exception 'Date re-enable failed'; end if;
 reset role;
 for n in 1..20 loop insert into public.tenant_escalation_contacts(id,tenant_id,label,contact_name,email,phone,enabled,position) values(gen_random_uuid(),target,'Active cap '||n,'Fictional',null,null,true,100+n); end loop;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 select config_revision into revision from public.tenant_setup_state where tenant_id=target;
 set local role authenticated;
 result:=public.onboarding_history_reenable(jsonb_build_object('tenant_id',target,'request_id',gen_random_uuid(),'expected_config_revision',revision,'kind','escalation_contacts','row_id',disabled_contact,'payload',jsonb_build_object('label','Office','contact_name','Fictional Manager','email','history-private@example.invalid','phone',null,'position',1)));
 if result->>'status'<>'validation_error' then raise exception 'Contact active cap overflow accepted'; end if;
 result:=public.onboarding_snapshot(target);
 if exists(select 1 from jsonb_array_elements(result->'snapshot'->'services') item where item->>'id'=second_service::text or item->>'enabled'<>'true') then raise exception 'Normal snapshot leaked disabled history after history APIs'; end if;
 reset role;
end; $$;

rollback;

