import { beforeEach, describe, expect, it, vi } from "vitest";
const h=vi.hoisted(()=>({getUser:vi.fn(),rpc:vi.fn(),member:vi.fn(),revalidate:vi.fn(),configured:true}));
vi.mock("@/lib/supabase/config",()=>({isSupabaseConfigured:()=>h.configured}));
vi.mock("@/lib/supabase/server",()=>({createClient:async()=>({auth:{getUser:h.getUser},rpc:h.rpc,from:()=>({select:()=>({eq:()=>({eq:()=>({maybeSingle:h.member})})})})})}));
vi.mock("next/cache",()=>({revalidatePath:h.revalidate}));
vi.mock("next/navigation",()=>({unstable_rethrow:(e:unknown)=>{if(e instanceof Error && e.message==='NEXT_CONTROL') throw e;}}));
import {saveOnboardingConfiguration,saveOnboardingProgress,acceptOnboardingAccess} from "@/app/actions/onboarding";
import {getOnboardingSnapshot} from "@/lib/server/onboarding-rpc";
import {PENDING_ONBOARDING_READINESS} from "@/lib/onboarding-contracts";
const tenant='48000000-0000-4000-8000-000000000001',request='48000000-0000-4000-8000-000000000002',user='48000000-0000-4000-8000-000000000003',id='48000000-0000-4000-8000-000000000004';
const payload={name:'Fictional business',trade:'HVAC',timezone:'UTC',business_contact_name:'',business_email:null,business_phone:null};
const input=()=>({tenant_id:tenant,request_id:request,expected_config_revision:0,payload:{...payload}});
const saved=()=>({status:'saved',entity:'setup',id:tenant,version:1,config_revision:1});
const resume=()=>({tenant_id:tenant,request_id:request,expected_version:0,step_id:'profile'});
const invite=()=>({request_id:request,token:'A'.repeat(43)});
const accepted=()=>({status:'accepted',acceptance:{invitation_id:id,accepted_at:'2026-10-04T12:00:00.000000Z'},workspace:{id:tenant,name:'Fictional business'},role:'owner',entry:'setup'});
const ownerSnapshot=()=>({projection:'owner_setup',workspace:{id:tenant,name:'Fictional',trade:'HVAC',timezone:'UTC'},flow_version:'onboarding-v1',config_revision:0,profile:null,services:[{id,name:'Cooling',description:'Current service',enabled:true,position:0,version:1}],weekly_hours:[],exceptions:[{id,date:'2026-10-04',closed:true,intervals:[],active:true,version:1}],booking:null,escalation:[{id,label:'Office',contact_name:'Fictional contact',email:'office@example.invalid',phone:null,enabled:true,position:0,version:1}],resume_step:'profile',resume_version:0,readiness:PENDING_ONBOARDING_READINESS});
beforeEach(()=>{vi.resetAllMocks();h.configured=true;h.getUser.mockResolvedValue({data:{user:{id:user}},error:null});h.member.mockResolvedValue({data:{role:'owner'},error:null});h.rpc.mockResolvedValue({data:saved(),error:null});});
describe('onboarding boundary',()=>{
 it.each([{},null,{...input(),actor:user},{...input(),payload:{...payload,name:''}},{...input(),request_id:'bad'},{...input(),payload:{...payload,timezone:null}},{...input(),expected_config_revision:'0'}])('rejects malformed configuration before authentication/RPC',async value=>{expect((await saveOnboardingConfiguration('save_business_profile',value)).result.status).toBe('validation_error');expect(h.rpc).not.toHaveBeenCalled();expect(h.getUser).not.toHaveBeenCalled();expect(h.revalidate).not.toHaveBeenCalled();});
 it('rejects invalid command and oversized data before RPC',async()=>{expect((await saveOnboardingConfiguration('unknown' as never,input())).result.status).toBe('validation_error');await saveOnboardingConfiguration('save_business_profile',{...input(),payload:{...payload,business_contact_name:'x'.repeat(140000)}});expect(h.rpc).not.toHaveBeenCalled();});
 it.each([null,{id:user}])('denies anonymous/failed verified identity',async identity=>{h.getUser.mockResolvedValue({data:{user:identity},error:{message:'private auth detail'}});expect((await saveOnboardingConfiguration('save_business_profile',input())).result.status).toBe('unavailable');expect(h.rpc).not.toHaveBeenCalled();});
 it.each(['dispatcher','technician','viewer','invalid'])('denies config role %s before RPC',async role=>{h.member.mockResolvedValue({data:{role},error:null});expect((await saveOnboardingConfiguration('save_business_profile',input())).result.status).toBe('unavailable');expect(h.rpc).not.toHaveBeenCalled();});
 it('denies missing membership and safely maps membership errors',async()=>{h.member.mockResolvedValue({data:null,error:null});expect((await saveOnboardingConfiguration('save_business_profile',input())).result.status).toBe('unavailable');h.member.mockResolvedValue({data:null,error:{message:'private'}});expect((await saveOnboardingProgress(resume())).result.status).toBe('retryable_failure');expect(h.rpc).not.toHaveBeenCalled();});
 it.each(['owner','admin'])('allows %s with exact normalized args and preserved retry identity',async role=>{h.member.mockResolvedValue({data:{role},error:null});const original={...input(),payload:{...payload,name:'  Fictional business  '}};const result=await saveOnboardingConfiguration('save_business_profile',original);expect(result.result).toEqual(saved());expect(h.rpc).toHaveBeenCalledWith('onboarding_configure',{command:'save_business_profile',input:input()});expect(original.payload.name).toContain('  ');expect(h.revalidate).toHaveBeenCalledWith(`/workspaces/${tenant}`,'layout');});
 it('maps resume args/results without changing precondition',async()=>{h.rpc.mockResolvedValue({data:{status:'replayed',entity:'resume',id,version:2,config_revision:0},error:null});const result=await saveOnboardingProgress(resume());expect(result.result.status).toBe('replayed');expect(h.rpc).toHaveBeenCalledWith('onboarding_save_resume',{input:resume()});});
 it('accepts invitation without requiring existing membership',async()=>{h.rpc.mockResolvedValue({data:accepted(),error:null});expect((await acceptOnboardingAccess(invite())).result).toEqual(accepted());expect(h.member).not.toHaveBeenCalled();expect(h.rpc).toHaveBeenCalledWith('onboarding_accept_invitation',{input:invite()});});
 it.each(['accepted','already_accepted','replayed'])('decodes invite outcome %s',async status=>{h.rpc.mockResolvedValue({data:{...accepted(),status},error:null});expect((await acceptOnboardingAccess(invite())).result.status).toBe(status);expect(h.revalidate).toHaveBeenCalledTimes(1);});
 it('invalid invitation input never calls RPC or reveals validation details',async()=>{expect((await acceptOnboardingAccess({...invite(),role:'owner'})).result).toEqual({status:'unavailable'});expect(h.rpc).not.toHaveBeenCalled();});
 it.each([{status:'unavailable'},{status:'retryable_failure'},{status:'conflict',reason:'revision'},{status:'conflict',reason:'request_reuse'},{status:'conflict',reason:'version_exhausted'},{status:'validation_error',issues:[{field:'name',code:'invalid_text'}]}])('handles safe failure %j without revalidation',async data=>{h.rpc.mockResolvedValue({data,error:null});expect((await saveOnboardingConfiguration('save_business_profile',input())).result).toEqual(data);expect(h.revalidate).not.toHaveBeenCalled();});
 it.each([null,{...saved(),private:'secret'},{...saved(),version:0},{...saved(),entity:'resume'},{...saved(),id},{...saved(),config_revision:2},{status:'conflict',reason:'raw SQL'},{status:'validation_error',issues:[{field:'private secret',code:'invalid_text'}]}])('fails closed on corrupt configuration result',async data=>{h.rpc.mockResolvedValue({data,error:null});expect((await saveOnboardingConfiguration('save_business_profile',input())).result).toEqual({status:'retryable_failure'});expect(h.revalidate).not.toHaveBeenCalled();});
 it.each([{...accepted(),role:'root'},{...accepted(),entry:'go_live'},{...accepted(),acceptance:{invitation_id:id,accepted_at:'invalid'}},{...accepted(),token:'secret'}])('rejects corrupt invitation response',async data=>{h.rpc.mockResolvedValue({data,error:null});expect((await acceptOnboardingAccess(invite())).result.status).toBe('retryable_failure');expect(h.revalidate).not.toHaveBeenCalled();});
 it('preserves confirmed result when refresh fails',async()=>{h.revalidate.mockImplementation(()=>{throw new Error('private refresh');});const result=await saveOnboardingConfiguration('save_business_profile',input());expect(result.result).toEqual(saved());expect(result.refreshRequired).toBe(true);expect(result.message).toContain('confirmed');});
 it('preserves framework control flow',async()=>{h.getUser.mockRejectedValue(new Error('NEXT_CONTROL'));await expect(saveOnboardingConfiguration('save_business_profile',input())).rejects.toThrow('NEXT_CONTROL');});
 it('maps gateway and thrown errors safely without logs',async()=>{const warn=vi.spyOn(console,'warn'),error=vi.spyOn(console,'error');try{h.rpc.mockResolvedValue({data:saved(),error:{message:'private SQL',code:'PGRST202'}});const response=await saveOnboardingConfiguration('save_business_profile',input());expect(JSON.stringify(response)).not.toContain('private');h.rpc.mockRejectedValue(new Error('private provider'));expect((await acceptOnboardingAccess(invite())).result.status).toBe('retryable_failure');expect(warn).not.toHaveBeenCalled();expect(error).not.toHaveBeenCalled();expect(h.revalidate).not.toHaveBeenCalled();}finally{warn.mockRestore();error.mockRestore();}});
 it('fails closed when configuration is missing',async()=>{h.configured=false;expect((await saveOnboardingProgress(resume())).result.status).toBe('retryable_failure');expect(h.rpc).not.toHaveBeenCalled();});
});
describe('snapshot projection boundary',()=>{
 const basic=(role='viewer')=>({status:'available',snapshot:{projection:'workspace',workspace:{id:tenant,name:'Fictional'},role}});
 it('calls exact snapshot args and allows limited role',async()=>{h.member.mockResolvedValue({data:{role:'viewer'},error:null});h.rpc.mockResolvedValue({data:basic(),error:null});expect(await getOnboardingSnapshot(tenant)).toEqual(basic());expect(h.rpc).toHaveBeenCalledWith('onboarding_snapshot',{target:tenant});expect(h.revalidate).not.toHaveBeenCalled();});
 it('rejects foreign workspace and cross-role projection',async()=>{h.member.mockResolvedValue({data:{role:'viewer'},error:null});h.rpc.mockResolvedValue({data:{...basic(),snapshot:{...basic().snapshot,workspace:{id,name:'foreign'}}},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('retryable_failure');h.rpc.mockResolvedValue({data:basic('technician'),error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('retryable_failure');});
 it('strictly decodes complete bounded owner shape and pending readiness',async()=>{const snapshot=ownerSnapshot();h.rpc.mockResolvedValue({data:{status:'available',snapshot},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('available');h.rpc.mockResolvedValue({data:{status:'available',snapshot:{...snapshot,readiness:{...snapshot.readiness,hostedReady:true}}},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('retryable_failure');});
 it.each([
  ['disabled service',{services:[{...ownerSnapshot().services[0],enabled:false}]}],
  ['inactive exception',{exceptions:[{...ownerSnapshot().exceptions[0],active:false}]}],
  ['disabled escalation',{escalation:[{...ownerSnapshot().escalation[0],enabled:false}]}],
  ['too many services',{services:Array.from({length:101},(_,index)=>({...ownerSnapshot().services[0],id:`48000000-0000-4000-8000-${String(index).padStart(12,'0')}`}))}],
  ['too many contacts',{escalation:Array.from({length:21},(_,index)=>({...ownerSnapshot().escalation[0],id:`48000000-0000-4000-8001-${String(index).padStart(12,'0')}`}))}]
 ])('rejects over-broad owner current projection: %s',async(_label,patch)=>{h.rpc.mockResolvedValue({data:{status:'available',snapshot:{...ownerSnapshot(),...patch}},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('retryable_failure');});
 it('rejects sensitive extra keys in limited projection',async()=>{h.member.mockResolvedValue({data:{role:'viewer'},error:null});h.rpc.mockResolvedValue({data:{...basic(),snapshot:{...basic().snapshot,contacts:['private']}},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('retryable_failure');});
 it('rejects malformed tenant before session/RPC',async()=>{expect(await getOnboardingSnapshot('bad')).toEqual({status:'unavailable'});expect(h.getUser).not.toHaveBeenCalled();});
});

describe('additional result and denial cases',()=>{
 it('does not call RPC for malformed resume or anonymous invitation',async()=>{expect((await saveOnboardingProgress({...resume(),actor:user})).result.status).toBe('validation_error');h.getUser.mockResolvedValue({data:{user:null},error:null});expect((await acceptOnboardingAccess(invite())).result.status).toBe('unavailable');expect(h.rpc).not.toHaveBeenCalled();});
 it('rejects wrong resume entity and missing exception identity',async()=>{expect((await saveOnboardingProgress(resume())).result.status).toBe('retryable_failure');h.rpc.mockResolvedValue({data:{status:'saved',entity:'exception',id:null,version:1,config_revision:1},error:null});expect((await saveOnboardingConfiguration('upsert_hours_exception',{...input(),payload:{date:'2026-10-04',closed:true,intervals:[]}})).result.status).toBe('retryable_failure');expect(h.revalidate).not.toHaveBeenCalled();});
 it.each([{status:'membership_conflict'},{status:'unavailable'},{status:'conflict',reason:'request_reuse'}])('preserves safe invite denial without refresh',async data=>{h.rpc.mockResolvedValue({data,error:null});expect((await acceptOnboardingAccess(invite())).result).toEqual(data);expect(h.revalidate).not.toHaveBeenCalled();});
 it('decodes dispatcher current shape while rejecting sensitive or retained projections',async()=>{h.member.mockResolvedValue({data:{role:'dispatcher'},error:null});const snapshot={projection:'dispatcher_operations',workspace:{id:tenant,name:'Fictional',trade:'HVAC',timezone:'UTC'},config_revision:0,services:[{id,name:'Cooling',enabled:true}],weekly_hours:[],exceptions:[],booking:null};h.rpc.mockResolvedValue({data:{status:'available',snapshot},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('available');h.rpc.mockResolvedValue({data:{status:'available',snapshot:{...snapshot,profile:{business_email:'private'}}},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('retryable_failure');h.rpc.mockResolvedValue({data:{status:'available',snapshot:{...snapshot,services:[{id,name:'Disabled',enabled:false}]}},error:null});expect((await getOnboardingSnapshot(tenant)).status).toBe('retryable_failure');});
});
